- hosts: all
  collections:
    - redhat.rhel_system_roles.timesync
  vars:
    timesync_ntp_servers:
      - hostname: 0.uk.pool.ntp.org
        iburst: yes
  roles:
    - redhat.rhel_system_roles.timesync
  tasks:
    - ping: